name: Trigger auto deployment for ct-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ct-container-AutoDeployTrigger-24d93a1a-c8a4-4b5c-8f63-3959f399a0d2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CTCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CTCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CTCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ctacaicms.azurecr.io
          registryUsername: ${{ secrets.CTCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CTCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: ct-container
          resourceGroup: Container-Instance-Rg
          imageToBuild: ctacaicms.azurecr.io/ct-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


